### ISSUE TITLE
Does not work with CE 2.14.0 :-(

### ISSUE THREAD

**Issue by tuxedo0801** [Ilhasoft/portainer-cli#8]
Tried to use this CLI to integrate container deployment via bitbucket pipeline... Seems to no longer work.

```
+ portainer-cli login apiuser apipassword
Traceback (most recent call last):
  File "/usr/local/bin/portainer-cli", line 6, in <module>
    plac.call(p.main)
  File "/usr/local/lib/python3.11/site-packages/plac_core.py", line 436, in call
    cmd, result = parser.consume(arglist)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plac_core.py", line 287, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/portainer_cli/__init__.py", line 260, in main
    plac.call(self.login, args)
  File "/usr/local/lib/python3.11/site-packages/plac_core.py", line 436, in call
    cmd, result = parser.consume(arglist)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plac_core.py", line 287, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/portainer_cli/__init__.py", line 105, in login
    response = self.request(
               ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/portainer_cli/__init__.py", line 236, in request
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://myportainer.tld:9443/api/auth
```

Seems that API has changed? Would also recommend to switch to access token instead of user/pass.

**Comment by mindesik** [comment]
Same error, not working with ce 2.18
